# Lightweight runtime image. The server only serves the prebuilt static client,
# so the image ships ONLY the server's production deps (express, dotenv).
# Build/dev deps (astro, sharp, sass, typescript, eslint, @types/*) are never installed
# here — they exist solely to produce the dist/ artifacts in CI, which we copy in below.
FROM node:22-alpine
ENV NODE_ENV=production

# pnpm is provided by Corepack, pinned via the root package.json "packageManager" field.
RUN corepack enable

WORKDIR /app

# A frozen, workspace-scoped install needs the lockfile, the workspace config, and ALL
# package manifests (pnpm validates the lockfile against the whole workspace before filtering).
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY packages/client/package.json ./packages/client/
COPY packages/server/package.json ./packages/server/

# Install ONLY the server package's production dependencies (express, dotenv), pinned by the
# single root lockfile. --ignore-scripts avoids running any dependency lifecycle scripts.
RUN pnpm install --frozen-lockfile --prod --filter=terjeofnorway.no-server --ignore-scripts

# Prebuilt artifacts produced in CI by `pnpm run build`.
# server.js resolves the client at ../../client/dist relative to its own location,
# so the dist folders must keep this relative layout.
COPY packages/server/dist ./packages/server/dist
COPY packages/client/dist ./packages/client/dist

# Runtime config (PORT, GIT_SHA) generated by the deploy workflow.
COPY .env ./packages/server/.env

# Expose port 8080
EXPOSE 8080

# Run the compiled server directly (no pnpm/workspace layer needed at runtime).
# cwd is /app/packages/server, so dotenv reads ./.env.
WORKDIR /app/packages/server
CMD ["node", "dist/server.js"]
