# Lightweight runtime image. The server only serves the prebuilt static client,
# so the image ships ONLY the server's production deps (express, dotenv).
# Build/dev deps (astro, sharp, sass, typescript, eslint, @types/*) are never installed
# here — they exist solely to produce the dist/ artifacts in CI, which we copy in below.
FROM node:22-alpine
WORKDIR /app/packages/server
ENV NODE_ENV=production

# Install only the server's production dependencies, pinned via its own lockfile.
# --ignore-scripts avoids running any dependency lifecycle scripts at build time.
COPY packages/server/package.json packages/server/package-lock.json ./
RUN npm ci --omit=dev --ignore-scripts && npm cache clean --force

# Prebuilt artifacts produced in CI by `npm run build`.
# server.js resolves the client at ../../client/dist relative to its own location,
# so the dist folders must keep this relative layout.
COPY packages/server/dist /app/packages/server/dist
COPY packages/client/dist /app/packages/client/dist

# Runtime config (PORT, GIT_SHA) generated by the deploy workflow.
COPY .env /app/packages/server/.env

# Expose port 8080
EXPOSE 8080

# Run the compiled server directly (no npm/workspace layer needed at runtime).
# cwd is /app/packages/server, so dotenv loads ./.env.
CMD ["node", "dist/server.js"]
