name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Create env file
        run: echo "PORT=8080" > .env
        run: echo "GIT_SHA=${{ github.sha }}" >> .env

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/terjeofnorway.no:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/terjeofnorway.no:latest

      - name: Pull & deploy container to DigitalOcean via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DIGITAL_OCEAN_SSH_ADDRESS }}
          username: root
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          script: |
            docker pull ghcr.io/terjeofnorway/terjeofnorway.no:${{ github.sha }}
            docker stop terjeofnorway.no || true
            docker rm terjeofnorway.no || true
            docker run -d \
              --name terjeofnorway.no \
              -p 8080:8080 \
              --restart unless-stopped \
              ghcr.io/terjeofnorway/terjeofnorway.no:${{ github.sha }}
